#!/bin/bash

function char {
  char='\x1b[1;94m @ \x1b[0m'
  echo -ne $char
}

function swing {
  spinner=('|' '/' '-' '\')
}

clear
tput civis
x=2
y=2
tput cup $y $x
char

while [ 1 ]
do
  read -rsn1 key

  if [[ $key = d ]]
  then
    clear
    x=$(($x + 1))
    tput cup $y $x
    char
  fi

  if [[ $key = a ]]
  then
    clear
    x=$(($x -1))
    tput cup $y $x
    char
  fi

  if [[ $key = w ]]
  then
    clear
    y=$(($y - 1))
    tput cup $y $x
    char
  fi

  if [[ $key = s ]]
  then
    clear
    y=$(($y + 1))
    tput cup $y $x
    char
  fi

  if [[ $key = i ]]
  then
    swing
    for i in "${spinner[@]}"
    do
      by=$(($y - 1))
      tput cup $by $x
      echo -ne "\x1b[93m $i \x1b[0m"
      sleep 0.1
      clear
      tput cup $y $x
      char
    done
  fi

  if [[ $key = k ]]
  then
    swing
    for i in "${spinner[@]}"
    do
      by=$(($y + 1))
      tput cup $by $x
      echo -ne "\x1b[93m $i \x1b[0m"
      sleep 0.1
      clear
      tput cup $y $x
      char
    done
  fi

  if [[ $key = l ]]
  then
    swing
    for i in "${spinner[@]}"
    do
      bx=$(($x + 2))
      tput cup $y $bx
      echo -ne "\x1b[93m $i \x1b[0m"
      sleep 0.1
      clear
      tput cup $y $x
      char
    done
  fi

  if [[ $key = j ]]
  then
    swing
    for i in "${spinner[@]}"
    do
      bx=$(($x - 2))
      tput cup $y $bx
      echo -ne "\x1b[93m $i \x1b[0m"
      sleep 0.1
      clear
      tput cup $y $x
      char
    done
  fi
done
